baseURL = 'https://blog.rishavs.in/'
languageCode = 'en-us'
title = "Rishav's Digital Garden"
theme = 'PaperMod'
googleAnalytics = "G-NPJY8ZT1P0"

########### PaperMod ###########
[params.homeInfoParams]
Title = "Welcome to My Digital Garden"
Content = """
### Developer / Tinkerer

A Software Developer, Tinkerer and Electronics & Communication Engineer who enjoys exploring every detail of technology.
"""

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/rishav-singh-0"

[[params.socialIcons]]
name = "github"
url = "https://github.com/rishav-singh-0"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/rishavs.in"

[[params.comments]]
comments=true

[[menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[menu.main]]
name = "Search"
url = "search/"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[params]
ShowShareButtons = false
ShowReadingTime = true
#ShowToc = true
#ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

################################

[markup.goldmark.renderer]
unsafe = true
